'use client';
import React, { useState } from 'react';
import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <Header>
          <MenuBtn active={active} setActive={setActive} />
        </Header>
        <AnimatePresence mode='wait'>
          {active && (
            <Nav active={active} setActive={setActive}>
              {navData.map(({ title, path, cls, id }, i) => (
                <NavItem
                  title={title}
                  path={path}
                  cls={cls}
                  key={id}
                  i={i}
                  active={active}
                />
              ))}
            </Nav>
          )}
        </AnimatePresence>
        {children}</body>
    </html>
  )
}
